import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>PIX SORTE</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <h1>Pix SORTE</h1>
      </main>
    </div>
  );
}
